# Generated by Django 2.0.6 on 2018-06-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20180604_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity_type', models.CharField(blank=True, choices=[('work_started', 'Work started'), ('work_stopped', 'Work stopped')], max_length=50)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.Bounty')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.Profile')),
            ],
        ),
    ]
